In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("listings.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Rows: 6574
Columns: 19

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,61878,MODERN LIVING AND FURNISHINGS,300211.0,1.462515e+18,Rita,NaN,District 2,32.816900,-96.820180,Entire home/apt,100.0,30.0,59,2026-03-30,0.31,1.0,312,2,NaN
1,795703,Amazing location walk to Downtown Dallas,4191322.0,1.462534e+18,Michelle,NaN,District 14,32.802353,-96.810707,Entire home/apt,179.0,30.0,71,2024-07-27,0.44,1.0,253,0,NaN
2,1277933,The Santa Fe Suite and Maxfield Parrish Suite,6904484.0,1.462548e+18,C. F. Sandy,NaN,District 11,32.924490,-96.790620,Private room,86.0,1.0,30,2019-11-09,0.27,1.0,319,0,NaN
3,1479800,SMU/Trendy Greenville/with Private Bath,3809024.0,1.462532e+18,Holly,NaN,District 14,32.831030,-96.763800,Private room,189.0,2.0,104,2026-06-14,0.67,3.0,106,2,NaN
4,1507428,"4323 McKinney Ave studio 8, WIFI, Parking",6063232.0,1.462697e+18,Joan,NaN,District 14,32.819610,-96.789960,Entire home/apt,53.0,30.0,75,2026-04-30,0.48,9.0,231,1,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              6574 non-null   int64
 1   name                            6574 non-null   object
 2   host_id                         6564 non-null   float64
 3   host_profile_id                 6562 non-null   float64
 4   host_name                       6562 non-null   object
 5   neighbourhood_group             0 non-null      float64
 6   neighbourhood                   6574 non-null   object
 7   latitude                        6574 non-null   float64
 8   longitude                       6574 non-null   float64
 9   room_type                       6574 non-null   object
 10  price                           6272 non-null   float64
 11  minimum_nights                  6570 non-null   float64
 12  number_of_reviews               6574 non-null   int64
 13  last_review                     5224 non-null   object
 14  reviews_per_month               5224 non-null   float64
 15  calculated_host_listings_count  6564 non-null   float64
 16  availability_365                6574 non-null   int64
 17  number_of_reviews_ltm           6574 non-null   int64
 18  license                         0 non-null      float64
dtypes: float64(10), int64(4), object(5)
memory usage: 976.0+ KB

In [ ]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
id,6574.0,NaN,NaN,NaN,1116866452629561728.0,582395011549537664.0,61878.0,805073045515408384.0,1340654551225297152.0,1592507013434738688.0,1708197032885143040.0
name,6574,6393,Luxury 2BD | Deep Ellum | Free Parking | Pool+Gym,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host_id,6564.0,NaN,NaN,NaN,23604816242964844.0,198004913492766336.0,43422.0,77470023.25,299860533.5,492645831.0,1706528210323299328.0
host_profile_id,6562.0,NaN,NaN,NaN,1487249980769480192.0,55923418356331976.0,1462507482221922816.0,1465280490076101888.0,1469064071994291712.0,1470335732367711744.0,1708683553977308416.0
host_name,6562,1986,Luxury Bookings Fze,102,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neighbourhood_group,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neighbourhood,6574,14,District 2,2037,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,6574.0,NaN,NaN,NaN,32.806318,0.063994,32.633617,32.77156,32.79848,32.822261,33.01545
longitude,6574.0,NaN,NaN,NaN,-96.795473,0.047938,-96.992697,-96.82539,-96.795539,-96.77002,-96.48124
room_type,6574,4,Entire home/apt,5646,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,6272.0,NaN,NaN,NaN,372.146365,717.879603,5.0,157.0,249.0,390.0,17150.0
minimum_nights,6570.0,NaN,NaN,NaN,5.606088,18.178395,1.0,1.0,1.0,2.0,365.0
number_of_reviews,6574.0,NaN,NaN,NaN,42.120779,85.830235,0.0,1.0,12.0,45.0,1482.0
last_review,5224,722,2026-05-31,327,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reviews_per_month,5224.0,NaN,NaN,NaN,2.063122,2.083947,0.01,0.53,1.525,3.01,53.33
calculated_host_listings_count,6564.0,NaN,NaN,NaN,12.09872,22.083472,1.0,1.0,3.0,11.0,102.0
availability_365,6574.0,NaN,NaN,NaN,259.103286,115.892824,0.0,176.0,317.0,353.0,365.0
number_of_reviews_ltm,6574.0,NaN,NaN,NaN,12.857925,18.689962,0.0,0.0,5.0,19.0,312.0
license,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.describe(include="all")

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
count,6.574000e+03,6574,6.564000e+03,6.562000e+03,6562,0.0,6574,6574.000000,6574.000000,6574,6272.000000,6570.000000,6574.000000,5224,5224.000000,6564.000000,6574.000000,6574.000000,0.0
unique,NaN,6393,NaN,NaN,1986,NaN,14,NaN,NaN,4,NaN,NaN,NaN,722,NaN,NaN,NaN,NaN,NaN
top,NaN,Luxury 2BD | Deep Ellum | Free Parking | Pool+Gym,NaN,NaN,Luxury Bookings Fze,NaN,District 2,NaN,NaN,Entire home/apt,NaN,NaN,NaN,2026-05-31,NaN,NaN,NaN,NaN,NaN
freq,NaN,9,NaN,NaN,102,NaN,2037,NaN,NaN,5646,NaN,NaN,NaN,327,NaN,NaN,NaN,NaN,NaN
mean,1.116866e+18,NaN,2.360482e+16,1.487250e+18,NaN,NaN,NaN,32.806318,-96.795473,NaN,372.146365,5.606088,42.120779,NaN,2.063122,12.098720,259.103286,12.857925,NaN
std,5.823950e+17,NaN,1.980049e+17,5.592342e+16,NaN,NaN,NaN,0.063994,0.047938,NaN,717.879603,18.178395,85.830235,NaN,2.083947,22.083472,115.892824,18.689962,NaN
min,6.187800e+04,NaN,4.342200e+04,1.462507e+18,NaN,NaN,NaN,32.633617,-96.992697,NaN,5.000000,1.000000,0.000000,NaN,0.010000,1.000000,0.000000,0.000000,NaN
25%,8.050730e+17,NaN,7.747002e+07,1.465280e+18,NaN,NaN,NaN,32.771560,-96.825390,NaN,157.000000,1.000000,1.000000,NaN,0.530000,1.000000,176.000000,0.000000,NaN
50%,1.340655e+18,NaN,2.998605e+08,1.469064e+18,NaN,NaN,NaN,32.798480,-96.795539,NaN,249.000000,1.000000,12.000000,NaN,1.525000,3.000000,317.000000,5.000000,NaN
75%,1.592507e+18,NaN,4.926458e+08,1.470336e+18,NaN,NaN,NaN,32.822261,-96.770020,NaN,390.000000,2.000000,45.000000,NaN,3.010000,11.000000,353.000000,19.000000,NaN
max,1.708197e+18,NaN,1.706528e+18,1.708684e+18,NaN,NaN,NaN,33.015450,-96.481240,NaN,17150.000000,365.000000,1482.000000,NaN,53.330000,102.000000,365.000000,312.000000,NaN

In [ ]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing %": (df.isnull().sum() / len(df) * 100).round(2)
})

missing.sort_values("Missing %", ascending=False)

                                Missing Values  Missing %
neighbourhood_group                       6574     100.00
license                                   6574     100.00
reviews_per_month                         1350      20.54
last_review                               1350      20.54
price                                      302       4.59
host_profile_id                             12       0.18
host_name                                   12       0.18
host_id                                     10       0.15
calculated_host_listings_count              10       0.15
minimum_nights                               4       0.06
id                                           0       0.00
name                                         0       0.00
longitude                                    0       0.00
latitude                                     0       0.00
neighbourhood                                0       0.00
room_type                                    0       0.00
number_of_reviews                            0       0.00
availability_365                             0       0.00
number_of_reviews_ltm                        0       0.00

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
print(df["room_type"].value_counts())

room_type
Entire home/apt    5646
Private room        832
Hotel room           67
Shared room          29
Name: count, dtype: int64

In [ ]:
print(df["neighbourhood"].value_counts())

neighbourhood
District 2     2037
District 14    1234
District 1      683
District 6      458
District 7      399
District 11     363
District 13     295
District 4      238
District 10     198
District 9      190
District 12     179
District 3      134
District 8      122
District 5       44
Name: count, dtype: int64

In [ ]:
print(df["price"].quantile([0.50, 0.75, 0.90, 0.95, 0.99]))

0.50     249.00
0.75     390.00
0.90     632.90
0.95     901.35
0.99    2145.29
Name: price, dtype: float64

In [ ]:
df[df["reviews_per_month"].isnull()]["number_of_reviews"].value_counts()

number_of_reviews
0    1350
Name: count, dtype: int64

In [ ]:
df[df["last_review"].isnull()]["number_of_reviews"].value_counts()

number_of_reviews
0    1350
Name: count, dtype: int64

In [ ]:
clean_df = df.copy()

In [ ]:
clean_df = clean_df.drop(columns=["neighbourhood_group", "license"])

In [ ]:
clean_df = clean_df.dropna(subset=["price"])

In [ ]:
clean_df["reviews_per_month"] = clean_df["reviews_per_month"].fillna(0)

In [ ]:
clean_df["last_review"] = pd.to_datetime(clean_df["last_review"])

In [ ]:
print("Original rows:", len(df))
print("Cleaned rows:", len(clean_df))
print("Original columns:", len(df.columns))
print("Cleaned columns:", len(clean_df.columns))

Original rows: 6574
Cleaned rows: 6272
Original columns: 19
Cleaned columns: 17

In [ ]:
clean_df.isnull().sum().sort_values(ascending=False)

last_review                       1273
host_profile_id                     12
host_name                           12
calculated_host_listings_count      10
host_id                             10
minimum_nights                       4
id                                   0
neighbourhood                        0
name                                 0
room_type                            0
longitude                            0
latitude                             0
price                                0
number_of_reviews                    0
reviews_per_month                    0
availability_365                     0
number_of_reviews_ltm                0
dtype: int64

In [ ]:
clean_df.head()

,id,name,host_id,host_profile_id,host_name,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
0,61878,MODERN LIVING AND FURNISHINGS,300211.0,1.462515e+18,Rita,District 2,32.816900,-96.820180,Entire home/apt,100.0,30.0,59,2026-03-30,0.31,1.0,312,2
1,795703,Amazing location walk to Downtown Dallas,4191322.0,1.462534e+18,Michelle,District 14,32.802353,-96.810707,Entire home/apt,179.0,30.0,71,2024-07-27,0.44,1.0,253,0
2,1277933,The Santa Fe Suite and Maxfield Parrish Suite,6904484.0,1.462548e+18,C. F. Sandy,District 11,32.924490,-96.790620,Private room,86.0,1.0,30,2019-11-09,0.27,1.0,319,0
3,1479800,SMU/Trendy Greenville/with Private Bath,3809024.0,1.462532e+18,Holly,District 14,32.831030,-96.763800,Private room,189.0,2.0,104,2026-06-14,0.67,3.0,106,2
4,1507428,"4323 McKinney Ave studio 8, WIFI, Parking",6063232.0,1.462697e+18,Joan,District 14,32.819610,-96.789960,Entire home/apt,53.0,30.0,75,2026-04-30,0.48,9.0,231,1

In [ ]:
clean_df[
    clean_df["minimum_nights"].isnull()
][[
    "id",
    "name",
    "price",
    "room_type",
    "minimum_nights"
]]

,id,name,price,room_type,minimum_nights
2838,1233320458284738176,NEW BUILD APT Near DT | King BD+Work Space+Bal...,117.0,Entire home/apt,NaN
4048,1467723174604580830,City Skyline View~Free Parking~5mins from Down...,143.0,Entire home/apt,NaN
4627,1548726488503269264,Bright & Private Bedroom + Bath,149.0,Private room,NaN
4688,1559021055042849675,Dallas Escape | Rooftop + Hot Tub | Vintage Ar...,380.0,Entire home/apt,NaN

In [ ]:
clean_df[
    clean_df["host_id"].isnull()
][[
    "id",
    "name",
    "host_id",
    "host_profile_id",
    "host_name",
    "calculated_host_listings_count"
]]

,id,name,host_id,host_profile_id,host_name,calculated_host_listings_count
5327,1634154001310690536,Designed by Sova,NaN,NaN,NaN,NaN
5328,1634154001798094744,Sova accessible,NaN,NaN,NaN,NaN
5499,1650773891008195585,"Warwick Melrose - Dallas, Selected by hotel",NaN,NaN,NaN,NaN
5577,1655714193524550173,Dlux king,NaN,NaN,NaN,NaN
5578,1655714193599261035,Loft King,NaN,NaN,NaN,NaN
5579,1655714193626310097,Dlux double queen,NaN,NaN,NaN,NaN
5704,1664716965676973236,Standard queen,NaN,NaN,NaN,NaN
6148,1688504596625070397,Studio suite - queen,NaN,NaN,NaN,NaN
6149,1688504597441765558,One bedroom suite - queen - mobility accessible,NaN,NaN,NaN,NaN
6150,1688504597931305172,Studio suite - queen - mobility accessible - roll,NaN,NaN,NaN,NaN

In [ ]:
clean_df.nlargest(20, "price")[[
    "id",
    "name",
    "neighbourhood",
    "room_type",
    "price",
    "minimum_nights",
    "number_of_reviews",
    "availability_365"
]]

,id,name,neighbourhood,room_type,price,minimum_nights,number_of_reviews,availability_365
3528,1392020810836476414,Designer MCM Home + Pool | Preston Hollow Area,District 13,Entire home/apt,17150.0,7.0,0,125
5942,1676812251185626779,Private 2+ Acre Estate. 15 min ATT Stadium FIFA.,District 3,Entire home/apt,15936.0,1.0,0,362
525,40135194,"Dallas Mansion great for Events, Wedding, Pict...",District 13,Entire home/apt,13512.0,7.0,0,365
991,52965158,Villa Oasis | Heated Pool & Hot tub by RelaxSTR,District 11,Entire home/apt,12666.0,2.0,35,183
5964,1678152111013112222,King Room Near Central Dentist DAL,District 13,Entire home/apt,12240.0,1.0,0,365
2107,1000198676954534534,ZZ Moda Lux 2BR American Airlines Center - K,District 6,Entire home/apt,10050.0,1.0,82,262
2108,1000209888255962567,ZZ Moda Lux Studio American Airlines Center - L,District 6,Entire home/apt,10050.0,1.0,43,294
1505,737374549242917591,ZzZ,District 14,Entire home/apt,10000.0,1.0,8,67
1506,737397138559046049,ZzZ,District 14,Entire home/apt,10000.0,1.0,5,67
1753,861861971513923638,ZZ Moda Lux Studio - D,District 6,Entire home/apt,10000.0,1.0,76,67
1754,861891078065080326,ZZ Moda Lux 1BR - B,District 6,Entire home/apt,10000.0,1.0,103,67
1755,861895782761648637,ZZ Moda Lux 1BR near American Airlines Center - C,District 6,Entire home/apt,10000.0,1.0,97,67
1756,861898844850538916,ZZ Moda Lux 1BR - E,District 6,Entire home/apt,10000.0,1.0,67,67
1805,883705019760996273,ZZ Moda Lux 1BR - A,District 6,Entire home/apt,10000.0,1.0,79,67
2074,987649827163175749,ZZ Moda Lux Studio American Airlines Center - G,District 6,Entire home/apt,10000.0,1.0,43,351
2075,987681500624961994,ZZ Moda Lux Studio American Airlines Center - I,District 6,Entire home/apt,10000.0,1.0,39,351
2095,995057345950205310,ZZ Moda Lux 1BR American Airlines Center - J,District 6,Entire home/apt,10000.0,1.0,50,67
4119,1478373059754618641,Guest house,District 7,Private room,9130.0,1.0,8,365
5558,1654864582950092660,Modern home in highland park neighborhood. 2,District 14,Entire home/apt,8676.0,3.0,0,177
5415,1642289922057132315,dfdf,District 10,Entire home/apt,7980.0,1.0,0,365

In [ ]:
clean_df["minimum_nights"] = clean_df["minimum_nights"].fillna(
    clean_df["minimum_nights"].median()
)

In [ ]:
price_99th = clean_df["price"].quantile(0.99)

clean_df["is_price_outlier"] = (
    clean_df["price"] > price_99th
)

In [ ]:
print("99th percentile price:", price_99th)
print("Price outliers:", clean_df["is_price_outlier"].sum())

99th percentile price: 2145.29
Price outliers: 63

In [ ]:
clean_df.isnull().sum().sort_values(ascending=False)

last_review                       1273
host_profile_id                     12
host_name                           12
host_id                             10
calculated_host_listings_count      10
id                                   0
name                                 0
longitude                            0
latitude                             0
neighbourhood                        0
price                                0
room_type                            0
number_of_reviews                    0
minimum_nights                       0
reviews_per_month                    0
availability_365                     0
number_of_reviews_ltm                0
is_price_outlier                     0
dtype: int64

In [ ]:
clean_df["is_price_outlier"].value_counts()

is_price_outlier
False    6209
True       63
Name: count, dtype: int64

In [ ]:
clean_df = clean_df.drop(
    columns=["host_profile_id", "host_name"]
)

In [ ]:
print("Rows:", len(clean_df))
print("Columns:", len(clean_df.columns))
print(clean_df.columns.tolist())

Rows: 6272
Columns: 16
['id', 'name', 'host_id', 'neighbourhood', 'latitude', 'longitude', 'room_type', 'price', 'minimum_nights', 'number_of_reviews', 'last_review', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'number_of_reviews_ltm', 'is_price_outlier']

In [ ]:
clean_df["price_capped"] = clean_df["price"].clip(
    upper=price_99th
)

In [ ]:
print("Rows:", len(clean_df))
print("Columns:", len(clean_df.columns))
print("\nColumns:")
print(clean_df.columns.tolist())

print("\nMissing values:")
print(clean_df.isnull().sum().sort_values(ascending=False))

print("\nPrice statistics:")
print(clean_df[["price", "price_capped"]].describe())

Rows: 6272
Columns: 17

Columns:
['id', 'name', 'host_id', 'neighbourhood', 'latitude', 'longitude', 'room_type', 'price', 'minimum_nights', 'number_of_reviews', 'last_review', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365', 'number_of_reviews_ltm', 'is_price_outlier', 'price_capped']

Missing values:
last_review                       1273
calculated_host_listings_count      10
host_id                             10
id                                   0
name                                 0
longitude                            0
room_type                            0
neighbourhood                        0
latitude                             0
minimum_nights                       0
price                                0
number_of_reviews                    0
reviews_per_month                    0
availability_365                     0
number_of_reviews_ltm                0
is_price_outlier                     0
price_capped                         0
dtype: int64

Price statistics:
              price  price_capped
count   6272.000000   6272.000000
mean     372.146365    335.058876
std      717.879603    318.288309
min        5.000000      5.000000
25%      157.000000    157.000000
50%      249.000000    249.000000
75%      390.000000    390.000000
max    17150.000000   2145.290000

In [ ]:
clean_df["host_id"] = clean_df["host_id"].astype("Int64")

clean_df["calculated_host_listings_count"] = (
    clean_df["calculated_host_listings_count"].astype("Int64")
)

clean_df["minimum_nights"] = clean_df["minimum_nights"].astype("Int64")

clean_df.to_csv("airbnb_dallas_clean.csv", index=False)